export const customPlants: Plant[] = [
  {
    id: "01K9Y2A7GDSBX4RNT1S5NEQM7S",
    name: "Aglaonema Beauty",
    description:
      "Aglaonema Beauty lives up to its name with bold, colorful leaves that brighten even low-light rooms. This plant is known for being very forgiving, tolerating occasional missed waterings and less-than-ideal light. Its compact, bushy form makes it perfect for side tables and shelves. It's a great choice for anyone wanting easy-care color without needing flowers.",
    waterNeeds: "MEDIUM",
    waterFrequency: "WEEKLY",
    waterAmount: "MODERATE",
    lightNeeds: "LOW",
    growthRate: "SLOW",
    price: 23,
    height: 10,
    createdAt: "2025-11-13T07:36:38.669Z",
    updatedAt: "2025-11-13T07:36:38.669Z",
    coverImg:
      "https://github.com/user-attachments/assets/32e4fb08-e637-4bb0-9c4a-a88d8b0a7afd",
    images: [],
    scientificName: "Aglaonema 'Beauty'",
    potSize: "SMALL",
    color: "PINK",
    maintenance: "LOW",
    locationType: "INDOOR",
    temperatureRange: "65-85°F",
    specialCare:
      "Keep away from cold drafts and allow the top of the soil to dry slightly between waterings",
    propagationMethods: ["DIVISION"],
    careSchedule: [],
    _count: { sprouty: 0 },
  },
  {
    id: "01K9Y2A5PWTQ7CS30BFN7E3JQ9",
    name: "Aglaonema Wishes",
    description:
      "Aglaonema Wishes is a cheerful, easygoing plant with splashes of pink and green across its leaves. It brightens low-light corners where other plants might struggle. This low-maintenance foliage plant tolerates some neglect and inconsistent watering. Its compact growth and colorful leaves make it ideal for desks, nightstands, or small living spaces.",
    waterNeeds: "MEDIUM",
    waterFrequency: "WEEKLY",
    waterAmount: "MODERATE",
    lightNeeds: "LOW",
    growthRate: "SLOW",
    price: 24,
    height: 10,
    createdAt: "2025-11-13T07:36:36.829Z",
    updatedAt: "2025-11-13T07:36:36.829Z",
    coverImg:
      "https://github.com/user-attachments/assets/6ed0cf07-36df-400b-809a-19973b51882d",
    images: [],
    scientificName: "Aglaonema 'Wishes'",
    potSize: "SMALL",
    color: "PINK",
    maintenance: "LOW",
    locationType: "INDOOR",
    temperatureRange: "65-85°F",
    specialCare:
      "Avoid harsh direct sun, which can wash out the colorful variegation",
    propagationMethods: ["DIVISION"],
    careSchedule: [],
    _count: { sprouty: 0 },
  },
  {
    id: "01K9Y29YJXJ9S864BH0XBRXNPM",
    name: "Areca Palm Plant",
    description:
      "The Areca Palm (Dypsis lutescens), also known as the Butterfly Palm or Golden Cane Palm, is a popular indoor plant admired for its elegant, feathery fronds and air-purifying qualities. Native to Madagascar, it thrives in bright, indirect light and adds a tropical touch to any space.",
    waterNeeds: "LOW",
    waterFrequency: "BIWEEKLY",
    waterAmount: "LIGHT",
    lightNeeds: "HIGH",
    growthRate: "SLOW",
    price: 22,
    height: 8,
    createdAt: "2025-11-13T07:36:29.365Z",
    updatedAt: "2025-11-13T07:36:29.365Z",
    coverImg:
      "https://github.com/user-attachments/assets/da2f4cb5-5d5c-46a7-bd25-2f2a67dbc6f0",
    images: [],
    scientificName: "Dypsis lutescens",
    potSize: "SMALL",
    color: "GREEN",
    maintenance: "LOW",
    locationType: "INDOOR",
    temperatureRange: "65-85°F",
    specialCare:
      "Use a gritty cactus mix and ensure the pot has excellent drainage",
    propagationMethods: ["STEM_CUTTING", "DIVISION"],
    careSchedule: [],
    _count: { sprouty: 0 },
  },
  {
    id: "01K9Y1ZGGHR6X1BCK5FP7BVMCQ",
    name: "Baltic Blue Pothos",
    description:
      "The Baltic Blue Pothos is a fast-growing vine with long, glossy leaves that deepen to a rich blue-green as they mature. As the plant grows larger and receives enough light, its leaves develop dramatic fenestrations, similar to a mini Monstera.",
    waterNeeds: "MEDIUM",
    waterFrequency: "WEEKLY",
    waterAmount: "MODERATE",
    lightNeeds: "MEDIUM",
    growthRate: "FAST",
    price: 26,
    height: 14,
    createdAt: "2025-11-13T07:30:47.442Z",
    updatedAt: "2025-11-13T07:30:47.442Z",
    coverImg:
      "https://github.com/user-attachments/assets/d3e0b7c7-11e2-484c-b900-613ffcf9acdd",
    images: [],
    scientificName: "Epipremnum pinnatum 'Baltic Blue'",
    potSize: "MEDIUM",
    color: "GREEN",
    maintenance: "LOW",
    locationType: "INDOOR",
    temperatureRange: "65-85°F",
    specialCare:
      "Provide a moss pole or trellis for larger leaves and increased fenestrations",
    propagationMethods: ["STEM_CUTTING"],
    careSchedule: [],
    _count: { sprouty: 0 },
  },
  {
    id: "01K9Y2AM72JEDBCPGKZP4A67C8",
    name: "Bromeliad Guzmania",
    description:
      "The Bromeliad Guzmania adds a bold, tropical accent with its bright, long-lasting flower spike rising from a rosette of glossy leaves. This plant is surprisingly easy-care, thriving in bright, indirect light and moderate humidity.",
    waterNeeds: "MEDIUM",
    waterFrequency: "WEEKLY",
    waterAmount: "LIGHT",
    lightNeeds: "MEDIUM",
    growthRate: "SLOW",
    price: 24,
    height: 12,
    createdAt: "2025-11-13T07:36:51.682Z",
    updatedAt: "2025-11-13T07:36:51.682Z",
    coverImg:
      "https://github.com/user-attachments/assets/91f1a8a5-389d-481c-aec1-bf2a88d8ef76",
    images: [],
    scientificName: "Guzmania hybrid",
    potSize: "SMALL",
    color: "YELLOW",
    maintenance: "LOW",
    locationType: "INDOOR",
    temperatureRange: "65-85°F",
    specialCare:
      "Keep the central cup half-filled with fresh water and flush it periodically",
    propagationMethods: ["DIVISION"],
    careSchedule: [],
    _count: { sprouty: 0 },
  },
];
